app2/config/routes.rb
Rails.application.routes.draw do
  get 'usersimple/new'
  get 'new'=>'usersimple#new'
  resources :articles do
  resources :comments
 end
  
  resources :user_stores

  resources :line_items

  resources :carts

  get 'store/index'

  resources :pictures

  resources :products

  get 'work/index'

  get 'work/choose_theme'

  get 'work/display_theme'

  resources :themes

  resources :images

  resources :values

  resources :users

  get 'main/about'

  get 'main/index'
  get 'discation'=>'article#new'
  get 'main/help'
  get  'main/contact'
  get  'help' => 'main#help'
  get  'index' => 'main#index'
  get  'about' => 'main#about'
  get  'products' => 'main#products'
  get  'pictures' => 'main#pictures'
  get  'store' => 'store#index'
   
   get  'user' => 'users#user'
   get  'value' => 'values#value'
   get  'image' => 'images#image'
   get  'theme' => 'themes#theme'
   
   get  'work' => 'work#index'
   get  'work' => 'work#choose_theme'
   get  'work' => 'work#display_theme'
    get 'carts'=>'carts#new'
    get 'usersStore'=>'user_stores#new'

    root 'main#about'

end

app2/app/models/article.rb
class Article < ActiveRecord::Base
#class Article < ApplicationRecord
has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 2 }
end
#end

app2/app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  cart = Cart.find()
  puts "Количество выбранных картинок:#{cart.line_items.count}"
end

app2/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app2/app/models/image.rb
class Image < ActiveRecord::Base
   belongs_to :theme
end

#class Image < ApplicationRecord
# belongs_to :theme
#end

app2/app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  
end

app2/app/models/picture.rb
class Picture < ActiveRecord::Base
end

app2/app/models/product.rb
class Product < ActiveRecord::Base
  #validates:title, :description, :image_url, presence:  true
  #validates :rate, numericality: {greate_than_or_equal_to: 1}
  
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  private
  def ensure_not_referenced_by_any_line_item
    if line_item.empty?
      return true
    else
      errors.add(:base, 'существуют позиции')
      return false
    end
  end

end

app2/app/models/theme.rb
class Theme < ActiveRecord::Base
  has_many :images
end
#class Theme < ApplicationRecord
#has_many :images
#end

app2/app/models/user.rb
class User < ActiveRecord::Base
end

app2/app/models/user_store.rb
class UserStore < ActiveRecord::Base
  validates:name, presence:true, uniqueness:true
   
  has_secure_password
end

app2/app/models/value.rb
class Value < ActiveRecord::Base
end

app2/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:name, :file, :av_value)
    end
end

app2/app/helpers/articles_helper.rb
module ArticlesHelper
end

app2/app/helpers/carts_helper.rb
module CartsHelper
end

app2/app/helpers/comments_helper.rb
module CommentsHelper
end

app2/app/helpers/images_helper.rb
module ImagesHelper
end

app2/app/helpers/main_helper.rb
module MainHelper
end

app2/app/helpers/pictures_helper.rb
module PicturesHelper
end

app2/app/helpers/store_helper.rb
module StoreHelper
end

app2/app/helpers/themes_helper.rb
module ThemesHelper
end

app2/app/helpers/users_helper.rb
module UsersHelper
end

app2/app/helpers/values_helper.rb
module ValuesHelper
end

app2/app/helpers/work_helper.rb
module WorkHelper
end

app2/app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :file %><br>
    <%= f.text_field :file %>
  </div>
  <div class="field">
    <%= f.label :av_value %><br>
    <%= f.text_field :av_value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app2/app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app2/app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>File</th>
      <th>Av value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.name %></td>
        <td><%= image.file %></td>
        <td><%= image.av_value %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app2/app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app2/app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @image.name %>
</p>

<p>
  <strong>File:</strong>
  <%= @image.file %>
</p>

<p>
  <strong>Av value:</strong>
  <%= @image.av_value %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>