app2/config/routes.rb
Rails.application.routes.draw do
  get 'usersimple/new'
  get 'new'=>'usersimple#new'
  resources :articles do
  resources :comments
 end
  
  resources :user_stores

  resources :line_items

  resources :carts

  get 'store/index'

  resources :pictures

  resources :products

  get 'work/index'

  get 'work/choose_theme'

  get 'work/display_theme'

  resources :themes

  resources :images

  resources :values

  resources :users

  get 'main/about'

  get 'main/index'
  get 'discation'=>'article#new'
  get 'main/help'
  get  'main/contact'
  get  'help' => 'main#help'
  get  'index' => 'main#index'
  get  'about' => 'main#about'
  get  'products' => 'main#products'
  get  'pictures' => 'main#pictures'
  get  'store' => 'store#index'
   
   get  'user' => 'users#user'
   get  'value' => 'values#value'
   get  'image' => 'images#image'
   get  'theme' => 'themes#theme'
   
   get  'work' => 'work#index'
   get  'work' => 'work#choose_theme'
   get  'work' => 'work#display_theme'
    get 'carts'=>'carts#new'
    get 'usersStore'=>'user_stores#new'

    root 'main#about'

end

app2/app/models/article.rb
class Article < ActiveRecord::Base
#class Article < ApplicationRecord
has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 2 }
end
#end

app2/app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  cart = Cart.find()
  puts "Количество выбранных картинок:#{cart.line_items.count}"
end

app2/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app2/app/models/image.rb
class Image < ActiveRecord::Base
   belongs_to :theme
end

#class Image < ApplicationRecord
# belongs_to :theme
#end

app2/app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  
end

app2/app/models/picture.rb
class Picture < ActiveRecord::Base
end

app2/app/models/product.rb
class Product < ActiveRecord::Base
  #validates:title, :description, :image_url, presence:  true
  #validates :rate, numericality: {greate_than_or_equal_to: 1}
  
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  private
  def ensure_not_referenced_by_any_line_item
    if line_item.empty?
      return true
    else
      errors.add(:base, 'существуют позиции')
      return false
    end
  end

end

app2/app/models/theme.rb
class Theme < ActiveRecord::Base
  has_many :images
end
#class Theme < ApplicationRecord
#has_many :images
#end

app2/app/models/user.rb
class User < ActiveRecord::Base
end

app2/app/models/user_store.rb
class UserStore < ActiveRecord::Base
  validates:name, presence:true, uniqueness:true
   
  has_secure_password
end

app2/app/models/value.rb
class Value < ActiveRecord::Base
end

app2/app/helpers/articles_helper.rb
module ArticlesHelper
end

app2/app/helpers/carts_helper.rb
module CartsHelper
end

app2/app/helpers/images_helper.rb
module ImagesHelper
end

app2/app/helpers/main_helper.rb
module MainHelper
end

app2/app/helpers/store_helper.rb
module StoreHelper
end

app2/app/helpers/themes_helper.rb
module ThemesHelper
end

app2/app/helpers/users_helper.rb
module UsersHelper
end

app2/app/helpers/values_helper.rb
module ValuesHelper
end

app2/app/helpers/work_helper.rb
module WorkHelper
end

app2/app/views/add/_footer.html.erb
<footer class="foot">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12  col-md-12  col-lg-12">
        <div class="foot-cont"> 
          <div class="foot-icon"><i class="fa fa-twitter"></i></div>
          <div class="foot-icon"><i class="fa fa-facebook"></i></div>
          <div class="foot-icon"><i class="fa fa-instagram"></i></div>
          <div class="foot-icon"><i class="fa fa-yelp"></i></div>
        </div>
      </div>
    </div>
  </div>


  <ul class="foot-ul">
   <li class="home-item home-item--active"><a href="#" class=" home-item-link--active">О нас</a></li>
   <li class="home-item"><a href="#" class="home-item-link">Участники</a></li>
   <li class="home-item"><a href="#" class="home-item-link">Контакты</a></li>
   <li class="home-item"><a href="#" class="home-item-link">Конфедициальность</a></li>

 </ul>

 <div class="foot-sp">С-Петербург, 2017</div>

</footer>

app2/app/views/add/_header.html.erb
<header class="beaty-header">
	<div class="container">
      <div class="row">
		
				<div class="col-xs-6 col-sm-12 col-md-2 col-lg-2">
					<!--<a href="" class="home-logo"><div class="log">Logo</div></a>-->
         <a href="" class="home-logo"><div class="log"><%= link_to image_tag("logo.jpg",alt:"logotip") %></div></a>
        </div>

        <div class="col-xs-6 hidden-sm hidden-md hidden-lg">
         <!--<a href="" class="home-logo"><div class="log">Logo</div></a>-->
         <div class="main-nav--cross"><i class="fa fa-bars" aria-hidden="true"></i></div>
       </div>

       <div class="hidden-xs col-sm-12 col-md-10 col-lg-10">
         <nav class="home-nav">
          <ul>
           <!--<li class="home-item home-item--active"><a href="#" class=" home-item-link--active">About</a></li>-->
           <li class="home-item home-item--active"><%= link_to "About", about_path, class:"home-item-link" %></li>
           
           <!--<li class="home-item"><a href="#" class="home-item-link">Contact</a></li>-->
         <!-- <li class="home-item"><#%= link_to "Contact", contact_path, class:"home-item-link" %></li>-->
           
           <!--<li class="home-item"><a href="#" class="home-item-link">Help</a></li>-->
           
            <li class="home-item"><%= link_to "Help", help_path, class:"home-item-link" %></li>
           <!--<li class="home-item"><a href="#" class="home-item-link">Index</a></li>-->
           <!--<li class="home-item"><#%= link_to "Index", index_path, class:"home-item-link" %></li>-->
           <li class="home-item"><%= link_to "Product", products_path, class:"home-item-link" %></li>
          <li class="home-item"><%= link_to "Store", store_path, class:"home-item-link" %></li>
          <!--<li class="home-item"><#%= link_to "User store", user_stores_path, class:"home-item-link" %></li>-->
          <li class="home-item"><%= link_to "Cart", carts_path, class:"home-item-link" %></li>
          <!--<li class="home-item"><#%= link_to "Items", line_items_path, class:"home-item-link" %></li>-->
          <li class="home-item"><%= link_to "User", users_path, class:"home-item-link" %></li>
          <li class="home-item"><%= link_to "Discation", articles_path, class:"home-item-link" %></li>
           
          
         </ul>
       </nav>


     </div>

     <div class="col-xs-12 hidden-sm hidden-md hidden-lg">
       <nav class="home-nav-sm">
        <ul>
         <!--<li class="home-item home-item--active"><a href="#" class=" home-item-link--active">О нас</a></li>
         <li class="home-item"><a href="#" class="home-item-link">Предложения</a></li>
         <li class="home-item"><a href="#" class="home-item-link">События</a></li>
         <li class="home-item"><a href="#" class="home-item-link">Контакты</a></li>-->
         <!--<li class="home-item home-item--active"><a href="#" class=" home-item-link--active">About</a></li>-->
           <li class="home-item home-item--active"><%= link_to "About", about_path, class:"home-item-link" %></li>
           
           <!--<li class="home-item"><a href="#" class="home-item-link">Contact</a></li>-->
         <!-- <li class="home-item"><#%= link_to "Contact", contact_path, class:"home-item-link" %></li>-->
           
           <!--<li class="home-item"><a href="#" class="home-item-link">Help</a></li>-->
           
            <li class="home-item"><%= link_to "Help", help_path, class:"home-item-link" %></li>
           <!--<li class="home-item"><a href="#" class="home-item-link">Index</a></li>-->
           <!--<li class="home-item"><#%= link_to "Index", index_path, class:"home-item-link" %></li>-->
           <li class="home-item"><%= link_to "Product", products_path, class:"home-item-link" %></li>
          <li class="home-item"><%= link_to "Store", store_path, class:"home-item-link" %></li>
          <li class="home-item"><%= link_to "User store", user_stores_path, class:"home-item-link" %></li>
          <li class="home-item"><%= link_to "Cart", carts_path, class:"home-item-link" %></li>
          <li class="home-item"><%= link_to "Items", line_items_path, class:"home-item-link" %></li>
          <li class="home-item"><%= link_to "User", users_path, class:"home-item-link" %></li>

       </ul>
     </nav>

   </div>	
   <!--<div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">
					<a href="" class="home-link">Book a tour</a>
				</div>-->
			</div>
		</div>			
	</header>
	<body>
	<div class="cssload-loader">
  <div class="cssload-inner cssload-one"></div>
  <div class="cssload-inner cssload-two"></div>
  <div class="cssload-inner cssload-three"></div>
</div>

<section class="home">
	<div class="container">
      <div class="col-md-12">
      
       <h1 class="home__title">Выберите действие.</h1>
       <p class="home-descr">Поставить оценку, попросить помощь, прочитать инструкцию.</p>
       <!--<a href="" class="home-descr-link">Заказать</a>-->
     </div>
   </div>
</section>
<div class="wrapper">
 
</div> 
 
 

app2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 
  <%= csrf_meta_tags %>
</head>
<body>
<body class='<%=controller.controller_name %>'>
<%= render 'add/header' %>
<div class="wrapper">
  <%= yield %>
</div>
<%= render 'add/footer' %>



</body>
</html>