app2/config/routes.rb
Rails.application.routes.draw do
  get 'usersimple/new'
  get 'new'=>'usersimple#new'
  resources :articles do
  resources :comments
 end
  
  resources :user_stores

  resources :line_items

  resources :carts

  get 'store/index'

  resources :pictures

  resources :products

  get 'work/index'

  get 'work/choose_theme'

  get 'work/display_theme'

  resources :themes

  resources :images

  resources :values

  resources :users

  get 'main/about'

  get 'main/index'
  get 'discation'=>'article#new'
  get 'main/help'
  get  'main/contact'
  get  'help' => 'main#help'
  get  'index' => 'main#index'
  get  'about' => 'main#about'
  get  'products' => 'main#products'
  get  'pictures' => 'main#pictures'
  get  'store' => 'store#index'
   
   get  'user' => 'users#user'
   get  'value' => 'values#value'
   get  'image' => 'images#image'
   get  'theme' => 'themes#theme'
   
   get  'work' => 'work#index'
   get  'work' => 'work#choose_theme'
   get  'work' => 'work#display_theme'
    get 'carts'=>'carts#new'
    get 'usersStore'=>'user_stores#new'

    root 'main#about'

end

app2/app/models/article.rb
class Article < ActiveRecord::Base
#class Article < ApplicationRecord
has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 2 }
end
#end

app2/app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  cart = Cart.find()
  puts "Количество выбранных картинок:#{cart.line_items.count}"
end

app2/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app2/app/models/image.rb
class Image < ActiveRecord::Base
   belongs_to :theme
end

#class Image < ApplicationRecord
# belongs_to :theme
#end

app2/app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  
end

app2/app/models/picture.rb
class Picture < ActiveRecord::Base
end

app2/app/models/product.rb
class Product < ActiveRecord::Base
  #validates:title, :description, :image_url, presence:  true
  #validates :rate, numericality: {greate_than_or_equal_to: 1}
  
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  private
  def ensure_not_referenced_by_any_line_item
    if line_item.empty?
      return true
    else
      errors.add(:base, 'существуют позиции')
      return false
    end
  end

end

app2/app/models/theme.rb
class Theme < ActiveRecord::Base
  has_many :images
end
#class Theme < ApplicationRecord
#has_many :images
#end

app2/app/models/user.rb
class User < ActiveRecord::Base
end

app2/app/models/user_store.rb
class UserStore < ActiveRecord::Base
  validates:name, presence:true, uniqueness:true
   
  has_secure_password
end

app2/app/models/value.rb
class Value < ActiveRecord::Base
end

app2/app/controllers/user_stores_controller.rb
class UserStoresController < ApplicationController
  before_action :set_user_store, only: [:show, :edit, :update, :destroy]

  # GET /user_stores
  # GET /user_stores.json
  def index
    @user_stores = UserStore.all
  end

  # GET /user_stores/1
  # GET /user_stores/1.json
  def show
  end

  # GET /user_stores/new
  def new
    @user_store = UserStore.new
  end

  # GET /user_stores/1/edit
  def edit
  end

  # POST /user_stores
  # POST /user_stores.json
  def create
    @user_store = UserStore.new(user_store_params)

    respond_to do |format|
      if @user_store.save
        format.html { redirect_to @user_store, notice: 'User store was successfully created.' }
        format.json { render :show, status: :created, location: @user_store }
      else
        format.html { render :new }
        format.json { render json: @user_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_stores/1
  # PATCH/PUT /user_stores/1.json
  def update
    respond_to do |format|
      if @user_store.update(user_store_params)
        format.html { redirect_to @user_store, notice: 'User store was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_store }
      else
        format.html { render :edit }
        format.json { render json: @user_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_stores/1
  # DELETE /user_stores/1.json
  def destroy
    @user_store.destroy
    respond_to do |format|
      format.html { redirect_to user_stores_url, notice: 'User store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_store
      @user_store = UserStore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_store_params
      params.require(:user_store).permit(:name, :password, :password_confirmation)
    end
    
end

app2/app/helpers/articles_helper.rb
module ArticlesHelper
end

app2/app/helpers/carts_helper.rb
module CartsHelper
end

app2/app/helpers/comments_helper.rb
module CommentsHelper
end

app2/app/helpers/images_helper.rb
module ImagesHelper
end

app2/app/helpers/main_helper.rb
module MainHelper
end

app2/app/helpers/store_helper.rb
module StoreHelper
end

app2/app/helpers/themes_helper.rb
module ThemesHelper
end

app2/app/helpers/user_stores_helper.rb
module UserStoresHelper
end

app2/app/helpers/users_helper.rb
module UsersHelper
end

app2/app/helpers/values_helper.rb
module ValuesHelper
end

app2/app/helpers/work_helper.rb
module WorkHelper
end

app2/app/views/user_stores/_form.html.erb
<%= form_for(@user_store) do |f| %>
  <% if @user_store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_store.errors.count, "error") %> prohibited this user_store from being saved:</h2>

      <ul>
      <% @user_store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app2/app/views/user_stores/edit.html.erb
<h1>Editing User Store</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_store %> |
<%= link_to 'Back', user_stores_path %>

app2/app/views/user_stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_stores.each do |user_store| %>
      <tr>
        <td><%= user_store.name %></td>
        <td><%= link_to 'Show', user_store %></td>
        <td><%= link_to 'Edit', edit_user_store_path(user_store) %></td>
        <td><%= link_to 'Destroy', user_store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User store', new_user_store_path %>

app2/app/views/user_stores/new.html.erb
<h1>New User Store</h1>

<%= render 'form' %>

<%= link_to 'Back', user_stores_path %>

app2/app/views/user_stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_store.name %>
</p>

<%= link_to 'Edit', edit_user_store_path(@user_store) %> |
<%= link_to 'Back', user_stores_path %>