app2/config/routes.rb
Rails.application.routes.draw do
  get 'usersimple/new'
  get 'new'=>'usersimple#new'
  resources :articles do
  resources :comments
 end
  
  resources :user_stores

  resources :line_items

  resources :carts

  get 'store/index'

  resources :pictures

  resources :products

  get 'work/index'

  get 'work/choose_theme'

  get 'work/display_theme'

  resources :themes

  resources :images

  resources :values

  resources :users

  get 'main/about'

  get 'main/index'
  get 'discation'=>'article#new'
  get 'main/help'
  get  'main/contact'
  get  'help' => 'main#help'
  get  'index' => 'main#index'
  get  'about' => 'main#about'
  get  'products' => 'main#products'
  get  'pictures' => 'main#pictures'
  get  'store' => 'store#index'
   
   get  'user' => 'users#user'
   get  'value' => 'values#value'
   get  'image' => 'images#image'
   get  'theme' => 'themes#theme'
   
   get  'work' => 'work#index'
   get  'work' => 'work#choose_theme'
   get  'work' => 'work#display_theme'
    get 'carts'=>'carts#new'
    get 'usersStore'=>'user_stores#new'

    root 'main#about'

end

app2/app/models/article.rb
class Article < ActiveRecord::Base
#class Article < ApplicationRecord
has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 2 }
end
#end

app2/app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  cart = Cart.find()
  puts "Количество выбранных картинок:#{cart.line_items.count}"
end

app2/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app2/app/models/image.rb
class Image < ActiveRecord::Base
   belongs_to :theme
end

#class Image < ApplicationRecord
# belongs_to :theme
#end

app2/app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  
end

app2/app/models/picture.rb
class Picture < ActiveRecord::Base
end

app2/app/models/product.rb
class Product < ActiveRecord::Base
  #validates:title, :description, :image_url, presence:  true
  #validates :rate, numericality: {greate_than_or_equal_to: 1}
  
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  private
  def ensure_not_referenced_by_any_line_item
    if line_item.empty?
      return true
    else
      errors.add(:base, 'существуют позиции')
      return false
    end
  end

end

app2/app/models/theme.rb
class Theme < ActiveRecord::Base
  has_many :images
end
#class Theme < ApplicationRecord
#has_many :images
#end

app2/app/models/user.rb
class User < ActiveRecord::Base
end

app2/app/models/user_store.rb
class UserStore < ActiveRecord::Base
  validates:name, presence:true, uniqueness:true
   
  has_secure_password
end

app2/app/models/value.rb
class Value < ActiveRecord::Base
end

app2/app/controllers/values_controller.rb
class ValuesController < ApplicationController
  before_action :set_value, only: [:show, :edit, :update, :destroy]

  # GET /values
  # GET /values.json
  def index
    @values = Value.all
  end

  # GET /values/1
  # GET /values/1.json
  def show
  end

  # GET /values/new
  def new
    @value = Value.new
  end

  # GET /values/1/edit
  def edit
  end

  # POST /values
  # POST /values.json
  def create
    @value = Value.new(value_params)

    respond_to do |format|
      if @value.save
        format.html { redirect_to @value, notice: 'Value was successfully created.' }
        format.json { render :show, status: :created, location: @value }
      else
        format.html { render :new }
        format.json { render json: @value.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /values/1
  # PATCH/PUT /values/1.json
  def update
    respond_to do |format|
      if @value.update(value_params)
        format.html { redirect_to @value, notice: 'Value was successfully updated.' }
        format.json { render :show, status: :ok, location: @value }
      else
        format.html { render :edit }
        format.json { render json: @value.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /values/1
  # DELETE /values/1.json
  def destroy
    @value.destroy
    respond_to do |format|
      format.html { redirect_to values_url, notice: 'Value was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_value
      @value = Value.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def value_params
      params.require(:value).permit(:user_id, :image_id, :value)
    end
end

app2/app/helpers/articles_helper.rb
module ArticlesHelper
end

app2/app/helpers/carts_helper.rb
module CartsHelper
end

app2/app/helpers/comments_helper.rb
module CommentsHelper
end

app2/app/helpers/images_helper.rb
module ImagesHelper
end

app2/app/helpers/main_helper.rb
module MainHelper
end

app2/app/helpers/pictures_helper.rb
module PicturesHelper
end

app2/app/helpers/store_helper.rb
module StoreHelper
end

app2/app/helpers/themes_helper.rb
module ThemesHelper
end

app2/app/helpers/users_helper.rb
module UsersHelper
end

app2/app/helpers/values_helper.rb
module ValuesHelper
end

app2/app/helpers/work_helper.rb
module WorkHelper
end

app2/app/views/values/_form.html.erb
<%= form_for(@value) do |f| %>
  <% if @value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@value.errors.count, "error") %> prohibited this value from being saved:</h2>

      <ul>
      <% @value.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :image_id %><br>
    <%= f.number_field :image_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.number_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app2/app/views/values/edit.html.erb
<h1>Editing Value</h1>

<%= render 'form' %>

<%= link_to 'Show', @value %> |
<%= link_to 'Back', values_path %>

app2/app/views/values/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Values</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Image</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @values.each do |value| %>
      <tr>
        <td><%= value.user_id %></td>
        <td><%= value.image_id %></td>
        <td><%= value.value %></td>
        <td><%= link_to 'Show', value %></td>
        <td><%= link_to 'Edit', edit_value_path(value) %></td>
        <td><%= link_to 'Destroy', value, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Value', new_value_path %>

app2/app/views/values/new.html.erb
<h1>New Value</h1>

<%= render 'form' %>

<%= link_to 'Back', values_path %>

app2/app/views/values/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @value.user_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @value.image_id %>
</p>

<p>
  <strong>Value:</strong>
  <%= @value.value %>
</p>

<%= link_to 'Edit', edit_value_path(@value) %> |
<%= link_to 'Back', values_path %>